# Generated by Django 5.0 on 2023-12-08 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='correct_percentage',
            field=models.FloatField(default=0.0, editable=False),
        ),
    ]
