# Generated by Django 5.0 on 2023-12-08 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_question_correct_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='correct_percentage',
        ),
    ]
