# Generated by Django 5.0 on 2023-12-08 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_remove_question_correct_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='chosen_choice',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='quiz.choice'),
            preserve_default=False,
        ),
    ]
