# Generated by Django 5.0 on 2023-12-08 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_alter_quizattempt_chosen_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizattempt',
            name='chosen_choice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.choice'),
        ),
    ]
